export const baseURL: string = 'http://192.168.10.2:8080/medicine'

// export const baseURL: string = 'http://10.11.11.166:8081/medicine'

// export const baseURL: string = 'http://106.14.199.233:15080/medicine'

export const QuestionnaireAddress: string = 'https://fcl4m4bwfn.feishu.cn/share/base/form/shrcnBj0sHhbzrBzxhhWesk1P3d'

export const HuaweiAccountUserAuthenticationProtocolAddress: string =
    'https://privacy.consumer.huawei.com/legal/id/authentication-terms.htm?code=CN&language=zh-CN'